---

- name: include limits.conf file
  include: limits.yml

- fail: msg="You can not use limits together with Suse 10.x releases"
  when: ansible_distribution_major_version == '10'

- template:
    src: limits_fragment.j2
    dest: "{{limits_d_dir}}/{{item.key}}.conf"
    owner: 'root'
    group: 'root'
    mode: 644
  with_dict: "{{limits_fragments}}"
