---

- name: create limits dir
  file:
    state: directory
    owner: 'root'
    group: 'root'
    mode: "{{limits_d_dir_mode}}"
    path: "{{limits_d_dir}}"

- name: configure limits_conf file
  template:
    dest: "{{config_file}}"
    src: limits.conf.j2
    owner: 'root'
    group: 'root'
    mode: "{{config_file_mode}}"

