---
# tasks file for ansible-role-pam

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-{{ansible_distribution_version}}.yml"

- name: include services when not empty
  include: service.yml
  when: _services

- name: include limits
  include: limits.yml

- name: include limits_fragments
  include: fragment.yml
  when: limits_fragments

- name: include accesslogin
  include: accesslogin.yml

- name: install package for redhat
  yum: name="{{package_name}}"
  when: ansible_os_family == 'RedHat'
- name: install package for suse
  zypper: name="{{package_name}}"
  when: ansible_os_family == 'Suse'
- name: install package for ubuntu
  apt: name="{{package_name}}"
  when: ansible_os_family == 'Debian'

- name: pam_d_login configure
  template:
    dest: "{{pam_d_login_path}}"
    src: "{{pam_d_login_template}}"
    owner: "{{pam_d_login_owner}}"
    group: "{{pam_d_login_group}}"
    mode: "{{pam_d_login_mode}}"

- name: pam_d_sshd configure
  template:
    dest: "{{pam_d_sshd_path}}"
    src: "{{pam_d_sshd_template}}"
    owner: "{{pam_d_sshd_owner}}"
    group: "{{pam_d_sshd_group}}"
    mode: "{{pam_d_sshd_mode}}"

- include:  RedHat-configure.yml
  when:  ansible_os_family == 'RedHat'

- include:  Debian-configure.yml
  when:  ansible_os_family == 'Debian'

- include:  Suse-configure.yml
  when:  ansible_os_family == 'Suse'
