---
# tasks file for ansible-role-pam

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-{{ansible_distribution_version}}.yml"

- name: include nsswitch
  include: ../../nsswitch/tasks/main.yml


